// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ShiftTrackingApp.Data;

#nullable disable

namespace ShiftTrackingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506120000_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftTrackingApp.Models.RefreshToken", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<bool>("IsRevoked").HasColumnType("bit");
                b.Property<string>("Token").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });
#pragma warning restore 612, 618
        }
    }
}
